# Generated by Django 5.2.16 on 2026-09-05 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this board is the one displayed first in the UI.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('position', models.PositiveIntegerField(help_text='Zero-based display order. Lower = further left.')),
                ('color', models.CharField(blank=True, default='', help_text='Hex color code for UI rendering (e.g. #4CAF50).', max_length=7)),
                ('wip_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of cards allowed in this column (optional).', null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.board')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_board_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'slug'), name='unique_column_slug_per_board'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'position'), name='unique_column_position_per_board'),
        ),
    ]
